import Logo from './components/Logo'
import Nav from './components/Nav'
import './globals.css'

export const metadata = {
  title: 'E-Commerce App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>

        <div className='bg-bgGray min-h-screen'>
          <div className='flex grow justify-center mt-1 md:hidden'>
            <Logo />
          </div>

          <div className='flex'>
            <Nav/>
            <div className=' flex-grow p-4'>
              {children}
            </div>
          </div>

        </div>

      </body>
    </html>
  )
}
